//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab16_Базы_данных_
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderList
    {
        public OrderList()
        {

        }
        public OrderList(int id, int orderId, int productId, int count)
        {
            Id = id;
            OrderId = orderId;
            ProductId = productId;
            Count = count;
        }
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public int Count { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Products { get; set; }
    }
}
