//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab16_Базы_данных_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderList = new HashSet<OrderList>();
        }

        public Order(int id, int idCustomer, DateTime orderDate, int trackNumber)
        {
            Id = id;
            IdCustomer = idCustomer;
            OrderDate = orderDate;
            TrackNumber = trackNumber;
        }

        public int Id { get; set; }
        public int IdCustomer { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int TrackNumber { get; set; }
    
        public virtual Customer Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderList> OrderList { get; set; }
    }
}
